-- Generated by Lava 2000

use work.all;

entity
  halfAdd
is
port
  -- clock
  ( clk : in bit

  -- inputs
  ; inp_1 : in bit
  ; inp_2 : in bit

  -- outputs
  ; outp_0 : out bit
  ; outp_1 : out bit
  );
end entity halfAdd;

architecture
  structural
of
  halfAdd
is
  signal w1 : bit;
  signal w2 : bit;
  signal w3 : bit;
  signal w4 : bit;
begin
  c_w2      : entity id    port map (clk, inp_1, w2);
  c_w3      : entity id    port map (clk, inp_2, w3);
  c_w1      : entity xor2  port map (clk, w2, w3, w1);
  c_w4      : entity and2  port map (clk, w2, w3, w4);

  -- naming outputs
  c_outp_0  : entity id    port map (clk, w1, outp_0);
  c_outp_1  : entity id    port map (clk, w4, outp_1);
end structural;
